# Notebook-4 NumPy Basics

# NumPy - 1d

In [1]:
import numpy as np 

In [2]:
my_array = np.array([0,11,22,33,44])
print(my_array)
print(type(my_array))

[ 0 11 22 33 44]
<class 'numpy.ndarray'>


In [3]:
my_array.shape

(5,)

In [4]:
my_array.ndim

1

In [5]:
my_array.size

5

In [6]:
my_array.dtype

dtype('int32')

In [7]:
my_float_array = np.array([31.1,1.02,6.22, 13.2,5.2])
print(type(my_float_array))
print(my_float_array.dtype)

<class 'numpy.ndarray'>
float64


In [8]:
print("my_array[0]:",my_array[0])
print("my_array[1]:",my_array[1])
print("my_array[2]:",my_array[2])
print("my_array[3]:",my_array[3])
print("my_array[4]:",my_array[4])


my_array[0]: 0
my_array[1]: 11
my_array[2]: 22
my_array[3]: 33
my_array[4]: 44


In [9]:
print("my_array[4]:",my_array[-1])
print("my_array[3]:",my_array[-2])
print("my_array[2]:",my_array[-3])
print("my_array[1]:",my_array[-4])
print("my_array[0]:",my_array[-5])

my_array[4]: 44
my_array[3]: 33
my_array[2]: 22
my_array[1]: 11
my_array[0]: 0


In [10]:
test_array = np.array([14, 34, 56, 89, 34])
test_array

array([14, 34, 56, 89, 34])

In [11]:
test_array[0] = 100
test_array

array([100,  34,  56,  89,  34])

In [12]:
test_array[4] = 0
test_array

array([100,  34,  56,  89,   0])

In [13]:
test_array[1:3]=300,400
test_array

array([100, 300, 400,  89,   0])

In [14]:
np.delete(test_array, 0)

array([300, 400,  89,   0])

In [15]:
select_list = [1,4]
selected_elements = test_array[select_list]
selected_elements 

array([300,   0])

In [16]:
mean_value = test_array.mean()
mean_value

177.8

In [17]:
standard_deviation = test_array.std()
standard_deviation

148.22739287999366

In [18]:
new_array = np.arange(0,10)
print(new_array, "\n")

print("type : ", type(new_array))
print("dimenstions : ", new_array.ndim)
print("shape : ", new_array.shape)
print("min : ", new_array.min())
print("max : ", new_array.max())
print("sum : ", new_array.sum())
print("mean : " , new_array.mean())
print("length : ", len(new_array))

[0 1 2 3 4 5 6 7 8 9] 

type :  <class 'numpy.ndarray'>
dimenstions :  1
shape :  (10,)
min :  0
max :  9
sum :  45
mean :  4.5
length :  10


# NumPy - 2d / matrix

In [19]:
new_list = [ 
                [11,12,13], 
                [21,22,23], 
                [31,32,33] 
           ]
print(new_list)
print(type(new_list))

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]
<class 'list'>


In [20]:
matrix = np.array(new_list)
print(matrix)
print(type(matrix))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>


In [21]:
matrix.ndim

2

In [22]:
matrix.shape

(3, 3)

In [23]:
matrix.size

9

In [24]:
matrix[1,2]

23

In [25]:
matrix[1][2]

23

In [26]:
matrix[0][0]

11

In [27]:
matrix[0][0:2]

array([11, 12])

In [28]:
matrix[0:2,2]

array([13, 23])

# Matrix Operations

In [29]:
matrix1 = np.array([[1,0],[0,1]]) 
matrix1

array([[1, 0],
       [0, 1]])

In [30]:
matrix2 = np.array([[2,1],[1,2]]) 
matrix2

array([[2, 1],
       [1, 2]])

In [31]:
result_matrix = 2 * matrix1
result_matrix

array([[2, 0],
       [0, 2]])

In [32]:
result_matrix = 1 + matrix1
result_matrix

array([[2, 1],
       [1, 2]])

In [33]:
result_matrix = matrix1 / 4
result_matrix

array([[0.25, 0.  ],
       [0.  , 0.25]])

In [34]:
result_matrix = matrix1 + matrix2
result_matrix

array([[3, 1],
       [1, 3]])

In [35]:
result_matrix = matrix1 * matrix2
result_matrix

array([[2, 0],
       [0, 2]])

In [36]:
result_matrix = matrix1 / matrix2
result_matrix

array([[0.5, 0. ],
       [0. , 0.5]])

In [37]:
matrix1 = np.array([[0,1,1],[1,0,1]])
matrix1

array([[0, 1, 1],
       [1, 0, 1]])

In [38]:
matrix2 = np.array([[1,1],[1,1],[-1,1]])
matrix2

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [39]:
result_matrix = np.dot(matrix1, matrix2)
result_matrix

array([[0, 2],
       [0, 2]])

In [ ]:
np.sin(result_matrix)

In [ ]:
matrix3 = np.array([[1,1],[2,2],[3,3]])
matrix3

In [ ]:
matrix3.T

In [ ]:
test_array = np.arange(20)
test_array

In [ ]:
m1 = test_array.reshape((5,4))
m1

In [ ]:
m1.shape

In [ ]:
m1.ndim

In [ ]:
m2 = np.reshape(test_array, (5,4), order="F")    # order = 'C' columns first     order='F' rows/first
m2

In [ ]:
m2.shape

In [ ]:
m3 = np.reshape(test_array, (5,4), order="C")    # order = 'C' columns first     order='F' rows/first
m3

In [ ]:
m3.shape

In [ ]:
m4 = np.reshape(test_array, (4,5), order="C")    # order = 'C' columns first     order='F' rows/first
m4

In [ ]:
m4.shape
